### ISSUE TITLE
Support dynamic values

### ISSUE THREAD

**Issue by kentcdodds** [styled-components/babel-plugin-polished#3]
I have [some utilities](https://github.com/kentcdodds/css-in-js-precompiler/blob/master/src/get-literalizers.js) that are able to derive the literal value of something, even across modules. I'm thinking of packaging this up into its own module. Would you be interested in adopting this in this plugin? I'd be happy to make a PR for it.

**Comment by jamiebuilds** [comment]
Oh boy, I need to share some stuff with you on how to resolve all that correctly. I'll DM you
