### ISSUE TITLE
Plugin is incorrectly parsing intentional null values.

### ISSUE THREAD

**Issue by bhough** [styled-components/babel-plugin-polished#4]
We have some mixins that intentionally take null to skip values. For example position:

`position('absolute', '20px', '20px', null, null)`

The babel plugin is stripping these null values out incorrectly and causing it to be parsed as:

`position('absolute', '20px', '20px')`

Which results in the incorrect final CSS: 

```css
position: absolute;
top: 20px;
right: 20px;
bottom: 20px;
left: 20px;
```

It should be:

```css
position: absolute;
top: 20px;
right: 20px;
```

I imagine this is impacting anywhere we use `null` in this manner.

**Comment by jamiebuilds** [comment]
Fixed
