### ISSUE TITLE
Method does not exist: hideVisually

### ISSUE THREAD

**Issue by rawrmonstar** [styled-components/babel-plugin-polished#5]
With the release of polished 1.9.0 a `hideVisually` mixin was added. When using this plugin and trying to import and use `hideVisually` I get the error:

> Method does not exist: hideVisually

Without using the babel plugin `hideVisually` is found and works OK so I think it has to do with this plugin.

I'll try to find the problem and submit a PR but I've never worked with a babel plugin before so I figured I should submit the issue in case a more experienced person sees an issue.

**Comment by alexanbj** [comment]
I had the same problem a few weeks ago, and I noticed in my yarn.lock that somehow both the old and the new version of babel-plugin-polished was resolved.

So for me the fix was to delete both yarn.lock and node_modules, then reinstall.
